language: java
jobs:
  include:
    - stage: Maven init
      script:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn compile
      - mvn package
    - stage: ant init
      script:
      - ant clean
      - ant init
      - ant compile
      - ant compile-test
      - ant jar
      - ant test