language: java
jobs:
  include:
    - stage: init
      script:
      - ant clean
      - ant compile
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: jar
      script: ant jar
